steps:
  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/iterary-479520/iterary-repo/iterary-frontend:$COMMIT_SHA'
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/iterary-479520/iterary-repo/iterary-frontend:latest'
      - './frontend'
    id: 'build-frontend'

  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/iterary-479520/iterary-repo/iterary-backend:$COMMIT_SHA'
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/iterary-479520/iterary-repo/iterary-backend:latest'
      - './backend'
    id: 'build-backend'

  # Push Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast2-docker.pkg.dev/iterary-479520/iterary-repo/iterary-frontend:$COMMIT_SHA'
    id: 'push-frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast2-docker.pkg.dev/iterary-479520/iterary-repo/iterary-frontend:latest'

  # Push Backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast2-docker.pkg.dev/iterary-479520/iterary-repo/iterary-backend:$COMMIT_SHA'
    id: 'push-backend'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast2-docker.pkg.dev/iterary-479520/iterary-repo/iterary-backend:latest'

images:
  - 'asia-southeast2-docker.pkg.dev/iterary-479520/iterary-repo/iterary-frontend:$COMMIT_SHA'
  - 'asia-southeast2-docker.pkg.dev/iterary-479520/iterary-repo/iterary-frontend:latest'
  - 'asia-southeast2-docker.pkg.dev/iterary-479520/iterary-repo/iterary-backend:$COMMIT_SHA'
  - 'asia-southeast2-docker.pkg.dev/iterary-479520/iterary-repo/iterary-backend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY